### ISSUE TITLE
Replace this repository with a new & improved Java Tracking SDK

### ISSUE THREAD

**Issue by mattab** [piwik/piwik-java-tracking#18]
Hello everyone,

I propose that we deprecate this repository `piwik-java-tracking` and instead make this new repository the official Java SDK for Piwik:  https://github.com/BCsorba/piwik-java-tracking-api

Ping @halfdan (author of this repository) @BCsorba  (author of the new Java SDK repository)

@halfdan maybe you have some feedback about this or the new Java SDK?

**Comment by mattab** [comment]
In the process i'd like to rename repository to `piwik-java-tracker` so it is consistent with:
 *  piwik-dotnet-tracker 
 *  piwik-php-tracker

**Comment by halfdan** [comment]
@mattab The library looks good. Happy to deprecate this library in favour of @BCsorba's library.

**Comment by mattab** [comment]
Done: new repository is available at: https://github.com/piwik/piwik-java-tracker
